#!/usr/bin/env python
import os
import sys

env = SConscript("godot-cpp/SConstruct")

customs = ["custom.py"]
profile = ARGUMENTS.get("profile", "")
if profile:
    if os.path.isfile(profile):
        customs.append(profile)
    elif os.path.isfile(profile + ".py"):
        customs.append(profile + ".py")
opts = Variables(customs, ARGUMENTS)

opts.Add(BoolVariable("debug_symbols", "Build with debugging symbols", True))

if env.get("is_msvc", False):
    if env["debug_symbols"]:
        env.Append(CCFLAGS=["/Zi", "/FS"])
        env.Append(LINKFLAGS=["/DEBUG:FULL"])
else:
    if env["debug_symbols"]:
        env.Append(CCFLAGS=["-g2"])

env.Append(CPPPATH=["src/"])
sources = Glob("src/*.cpp")

library = env.SharedLibrary(
        "../voxelgame/bins/core",
        source=sources,
    )

Default(library)