name: Continuous integration
on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 🐧 Linux (GCC)
            os: ubuntu-18.04
            platform: linux
            artifact-name: godot-cpp-linux-glibc2.27-x86_64-release
            artifact-path: bin/libgodot-cpp.linux.release.64.a

          - name: 🏁 Windows (x86_64, MSVC)
            os: windows-2019
            platform: windows
            artifact-name: godot-cpp-windows-msvc2019-x86_64-release
            artifact-path: bin/libgodot-cpp.windows.release.64.lib

          - name: 🏁 Windows (x86_64, MinGW)
            os: windows-2019
            platform: windows
            artifact-name: godot-cpp-linux-mingw-x86_64-release
            artifact-path: bin/libgodot-cpp.windows.release.64.a
            flags: use_mingw=yes

          - name: 🍎 macOS (universal)
            os: macos-11
            platform: osx
            artifact-name: godot-cpp-macos-universal-release
            artifact-path: bin/libgodot-cpp.osx.release.universal.a
            flags: macos_arch=universal

          - name: 🤖 Android (arm64)
            os: ubuntu-18.04
            platform: android
            artifact-name: godot-cpp-android-arm64-release
            artifact-path: bin/libgodot-cpp.android.release.arm64v8.a
            flags: android_arch=arm64v8

          - name: 🍏 iOS (arm64)
            os: macos-11
            platform: ios
            artifact-name: godot-cpp-ios-arm64-release
            artifact-path: bin/libgodot-cpp.ios.release.arm64.a

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python (for SCons)
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Linux dependencies
        if: ${{ matrix.platform == 'linux' }}
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qqq build-essential pkg-config

      - name: Install scons
        run: |
          python -m pip install scons

      - name: Setup MinGW for Windows/MinGW build
        if: ${{ matrix.platform == 'windows' && matrix.flags == 'use_mingw=yes' }}
        uses: egor-tensin/setup-mingw@v2

      - name: Build godot-cpp (debug)
        run: |
          scons platform=${{ matrix.platform }} target=debug generate_bindings=yes ${{ matrix.flags }} -j2

      - name: Build test without rebuilding godot-cpp (debug)
        run: |
          cd test
          scons platform=${{ matrix.platform }} target=debug ${{ matrix.flags }} build_library=no -j2

      - name: Build test and godot-cpp (release)
        run: |
          cd test
          scons platform=${{ matrix.platform }} target=release ${{ matrix.flags }} -j2

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact-name }}
          path: ${{ matrix.artifact-path }}
          if-no-files-found: error

  linux-cmake:
    name: Build (Linux, GCC, CMake)
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qqq build-essential pkg-config cmake

      - name: Build godot-cpp
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release .
          make -j $(nproc)

      - name: Build test GDNative library
        run: |
          cd test && cmake -DCMAKE_BUILD_TYPE=Release -DGODOT_HEADERS_PATH="../godot-headers" -DCPP_BINDINGS_PATH=".." .
          make -j $(nproc)

  linux-cmake-ninja:
    name: Build (Linux, GCC, CMake Ninja)
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qqq build-essential pkg-config cmake ninja-build

      - name: Build godot-cpp
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -GNinja .
          cmake --build . -j $(nproc)

      - name: Build test GDNative library
        run: |
          cd test && cmake -DCMAKE_BUILD_TYPE=Release -DGODOT_HEADERS_PATH="../godot-headers" -DCPP_BINDINGS_PATH=".." -GNinja .
          cmake --build . -j $(nproc)

  windows-msvc:
    name: Build (Windows, MSVC)
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python (for SCons)
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install scons

      - name: Build godot-cpp
        run: |
          scons target=release generate_bindings=yes -j $env:NUMBER_OF_PROCESSORS

      - name: Build test project
        run: |
          cd test
          scons target=release -j $env:NUMBER_OF_PROCESSORS

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: godot-cpp-windows-msvc2019-x86_64-release
          path: bin/libgodot-cpp.windows.release.64.lib
          if-no-files-found: error
  
  windows-msvc-cmake:
    name: Build (Windows, MSVC, CMake)
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build godot-cpp
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -G"Visual Studio 16 2019" .
          cmake --build .

      - name: Build test GDNative library
        run: |
          cd test && cmake -DCMAKE_BUILD_TYPE=Release -DGODOT_HEADERS_PATH="../godot-headers" -DCPP_BINDINGS_PATH=".." -G"Visual Studio 16 2019" .
          cmake --build .

  windows-mingw:
    name: Build (Windows, MinGW)
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python (for SCons)
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install scons

      - name: Setup MinGW for Windows/MinGW build
        uses: egor-tensin/setup-mingw@v2

      - name: Build godot-cpp
        run: |
          scons target=release generate_bindings=yes use_mingw=yes -j $env:NUMBER_OF_PROCESSORS

      #- name: Build test project (TODO currently not supported, leaving uncommented as a reminder to fix this)
      #  run: |
      #    cd test
      #    scons target=release use_mingw=yes -j $env:NUMBER_OF_PROCESSORS

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: godot-cpp-linux-mingw-x86_64-release
          path: bin/libgodot-cpp.windows.release.64.a
          if-no-files-found: error

  macos:
    name: Build (macOS, Clang, universal / x86_64 + arm64)
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python (for SCons)
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install scons

      - name: Build godot-cpp
        run: |
          scons target=release generate_bindings=yes -j $(sysctl -n hw.logicalcpu)

      - name: Build test project
        run: |
          cd test
          scons target=release -j $(sysctl -n hw.logicalcpu)

  static-checks:
    name: Static Checks (clang-format)
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Make apt sources.list use the default Ubuntu repositories
        run: |
          sudo rm -f /etc/apt/sources.list.d/*
          sudo cp -f misc/ci/sources.list /etc/apt/sources.list
          sudo apt-get update

      - name: Install dependencies
        run: |
          sudo apt-get install -qq dos2unix recode clang-format-11
          sudo update-alternatives --remove-all clang-format
          sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-11 100

      - name: Style checks via clang-format
        run: |
          bash ./misc/scripts/clang_format.sh
